export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const UPDATE_INGREDIENT_NAME = 'UPDATE_INGREDIENT_NAME';
export const UPDATE_INGREDIENT_PERCENT = 'UPDATE_INGREDIENT_PERCENT';
export const UPDATE_INGREDIENT_TYPE = 'UPDATE_INGREDIENT_TYPE';
export const UPDATE_INGREDIENT_HYDRATION = 'UPDATE_INGREDIENT_HYDRATION';
export const UPDATE_INGREDIENT_WEIGHT = 'UPDATE_INGREDIENT_WEIGHT';